### ISSUE TITLE
Arch Linux KDE - Cawbird Notifications Overload Taskbar

### ISSUE THREAD

**Issue by ThisNekoGuy** [IBBoard/cawbird#312] opened 2021-02-08 20:11 UTC
When not using Caw bird for an extended period of time, and I have a lot of direct messages, coming back to Cawbird floods KDE's notification system and crashes my taskbar.

**Comment by IBBoard** [comment] 2021-02-09 20:28
Do you know what all the notifications were - were there duplicates or notifications about the same threads? And how many people were you DMing (or were DMing you)?

Our code *should* just use GLib.Notifications to push a notification, and when the new DM comes in then it should withdraw the old notification and replace it with a new one saying "N new DMs" rather than the details ([src 1](https://github.com/IBBoard/cawbird/blob/master/src/DMThreadsPage.vala#L245-L258), [src 2](https://github.com/IBBoard/cawbird/blob/efd5e6c73e0196548bc9834c5163c110e214cf4e/src/NotificationManager.vala#L43-L62)).

It might be that KDE isn't handling GLib Notifications correctly (or at least the withdrawl requests).

([The docs](https://valadoc.org/gio-2.0/GLib.Application.send_notification.html) suggest that we might not even need to do the withdrawing step because using the same ID should override it, but that's legacy code)

**Comment by ThisNekoGuy** [comment] 2021-02-10 20:16
From what I was able to tell at the time, it was all from a single DM chat (I don't talk to many people through DM on Twitter).
Considering that there were many messages in between when I had last used Cawbird, I don't know if any of the notifications were duplicates, but I do know for sure that it was from a single conversation

**Comment by IBBoard** [comment] 2021-02-10 20:47
I've just done a quick test of this and can't recreate it in Gnome.

1) Send a DM from my test account (on the web) to my main account (with Cawbird open)
1) Wait
1) DM arrives, single notification shows the content of the DM
1) DO NOT read the DM or open the thread or anything
1) Send a second DM from the test account
1) Wait
1) DM arrives, notification is replaced with a "Test account sent you two DMs"
1) Open the thread (not touching the notification), notification is removed
1) Send three DMs in quick succession from the test account
1) Wait
1) DMs arrive, one notification is shown saying "Test account sent you three DMs" (although it flashed quite quickly before disappearing into the tray, which I think might be because it did a one, two and then three DM message

At no point did I have more than one notification, and every time a new DM came in then the existing notification was replaced.

**Comment by ThisNekoGuy** [comment] 2021-02-10 21:15
To be clear, Cawbird was not open when I received or sent DMs; it queued that information to notify me when I opened Cawbird at a later date.

I don't always have Cawbird open (I didn't see a setting that has it minimize to tray on launch so I don't have my system auto-start Cawbird on system startup).

**Comment by IBBoard** [comment] 2021-02-11 18:26
Ah, okay. That wasn't clear from the description. I thought "when not using Cawbird" just mean not using the app and it was running and stacking up notifications. This is why we have the bug reporting template, so that we can understand and recreate problems ;)

I'll have to check what we do at startup. We already had to put some code in for #137 because people got lots of notifications when they first logged in. I'd expect it to do similar notification supression at startup, but maybe it doesn't work when you've got more than one page of DMs and we've got to follow the "cursor" back to a previous page.

I'd still expect it to keep replacing the notifications if they're all for one conversation, though, because it should be calling exactly the same notification code each time.

**Comment by IBBoard** [comment] 2021-02-13 15:16
I used a different computer yesterday where I hadn't used Cawbird for a while. When I started it, I ended up with two notifications in my tray - one for one DM from one conversation (with the detail), and one for a conversation with seven DMs (a summary notification).

From what you've said, I'd have expected it to show eight notifications. Based on the code, it sent eight notifications but six of those replaced the preceding one for that conversation. If you saw one notification per DM (which should be one with details, and then a series of summary notifications with an increasing DM count) then I think that's a KDE bug in handling GLib.Notification.

**Comment by IBBoard** [comment] 2021-03-11 19:31
I can't recreate this, so until someone can show me an example of the notifications then I'm going to have to close it.

**Closed by IBBoard** 2021-03-11 19:31 UTC
Labels: info required, works for me

**Comment by ThisNekoGuy** [comment] 2021-03-11 20:08
@IBBoard 

It does something like this:

I had actually disabled notifications to avoid the glitchy overflow-spam that kept crashing the taskbar but it still logs them in the notification tray.

Now in this case, I don't _think_ I talk to my friend this much on Twitter but instead of just notifying me of just the number of "unread messages," it notifies me of all of them _individually_ on the app's startup which is somewhat unnecessary...

Being notified of individual messages would make more sense to me if the app was already open when the messages come in, instead of dumping it all in the notification tray at once like a mailman with a box full of mail dumping it all on a desk

![all_at_once](https://user-images.githubusercontent.com/28468662/110847114-6bd06900-82a4-11eb-8c34-3d8ab4fed0d5.png)

**Comment by IBBoard** [comment] 2021-03-12 19:45
Those are presumably all from the same conversation, rather than a dozen conversations with a suspiciously similar number of messages in them?

> I had actually disabled notifications to avoid the glitchy overflow-spam that kept crashing the taskbar but it still logs them in the notification tray.

I'm not sure I understand. You've disabled DM notifications, but you're still getting them? But they're somehow hidden now? Is this a "mute in KDE" disable rather than the Cawbird setting?

> Now in this case, I don't think I talk to my friend this much on Twitter but instead of just notifying me of just the number of "unread messages," it notifies me of all of them individually on the app's startup which is somewhat unnecessary...

The messages get "streamed" one-by-one (we actually fake the streaming, but the effect is the same). That means that we send one notification for every message because we never know whether it's the last one from the batch or whether another one is about to be sent.

BUT all notifications in a thread have the [same notification ID](https://github.com/IBBoard/cawbird/blob/efd5e6c73e0196548bc9834c5163c110e214cf4e/src/NotificationManager.vala#L43-L62), so previous messages can be removed and replaced. If that's not happening then that's either a somehow buggy build or KDE mishandling the GLib.Notification integration.

Also, we only send notifications if the DM is unread in Cawbird. Twitter doesn't tell us whether you read it elsewhere or not, but once it's in Cawbird then we check [whether we've received the DM before and stop processing](https://github.com/IBBoard/cawbird/blob/master/src/DMManager.vala#L110-L117), which prevents us notifying on ones you've already seen in the app. If you've not received 128+ DMs from the other person since you last used Cawbird then there's something going wrong there.

What version of Cawbird are you using? And which package (OBS, distro, Flatpak, Snap)?

**Comment by IBBoard** [comment] 2021-03-12 20:15
Okay, quick little test script - if you're able to compile Vala code. If you create a file called `notification.vala` with this content:

```
using GLib;
public class HelloWorld {
        static void main () {
                var application = new GLib.Application ("uk.co.ibboard.cawbird", GLib.ApplicationFlags.FLAGS_NONE);
                application.register ();
                var notification = new GLib.Notification ("Hello world");
                notification.set_body ("This is an example notification.");
                var Icon = new GLib.ThemedIcon ("dialog-information");
                notification.set_icon (Icon);
                print("Sending notification\n");
                var id = "test-id";
                application.send_notification (id, notification);
                GLib.Thread.usleep(5 * 1000 * 1000);
                print("Withdrawing notification\n");
                application.withdraw_notification (id);
                GLib.Thread.usleep(5 * 1000 * 1000);
                print("Sending new notification\n");
                application.send_notification (id, notification);
                GLib.Thread.usleep(5 * 1000 * 1000);
                print("Replacing notification\n");
                notification.set_body ("Different body");
                application.send_notification (id, notification);
        }
}
```


Then run `valac --pkg gio-2.0 notification.vala; ./notification`, it should:

* Show a notification
* Remove it by withdrawing the ID
* Show a notification
* Replace the notification by sending a new one with the same ID

If that doesn't work then the problem is in KDE. If that works then we need to look at why you're getting 120+ messages that it doesn't recognise as having seen before. And how it could be failing to set the right ID so that we can remove/replace them.

**Comment by ThisNekoGuy** [comment] 2021-03-13 23:44
To answer the first question, KDE lets you disable pop-ups but the notifications still stay in the tray's notification history; it's the pop-up notifications that were causing the issue

![Screenshot_20210313_173450](https://user-images.githubusercontent.com/28468662/111052683-f061e980-8454-11eb-99d8-8a338bede193.png)

And the notification spam was all from a single conversation with one individual, to be clear

And I'm using the Arch distro repository package of Cawbird

As for the test, the test did work as expected, with Cawbird closed.
I'll also place the terminal log here, but it it behaved as expected:
```vala
neko-san@ARCH ~/test> valac --pkg gio-2.0 notification.vala; ./notification
notification.vala:5.17-5.39: warning: unhandled error `GLib.Error'
                application.register ();
                ^^^^^^^^^^^^^^^^^^^^^^^
Compilation succeeded - 1 warning(s)
Sending notification
Withdrawing notification
Sending new notification
Replacing notification
neko-san@ARCH ~/test> 
```

![Screenshot_20210313_174309](https://user-images.githubusercontent.com/28468662/111052772-ebea0080-8455-11eb-8208-d2d46b7566e2.png)

**Comment by IBBoard** [comment] 2021-03-14 08:02
Sorry, I need a bit more clarity. Was the first pop-up withdrawn and then the second one replaced? Or did it just show all of them? Or is it not possible to tell because of timeouts or only one pop-up showing at once?

There's time delays in that script, so it wouldn't flood everything at once. But it should still do the withdraw/replace behaviour.

The fact that we're flooding the notification history appears to be an unhelpful "feature" of KDE. The whole point of explicitly withdrawing or replacing notifications with an ID is to replace and withdraw them because the old one is no longer relevant. If the desktop environment won't honour that then we can't help.

**Comment by ThisNekoGuy** [comment] 2021-03-14 17:49
The first pop up timed out but it did so at the same time that the script said it was being withdrawn

The second one appeared but timed out just when the script said it was being replaced, then the last one appeared as if a new notification was made; had I not already know it was supposed to be replaced, I would have thought it to be an entirely new one and KDE seemed to perceive it that way too as far as I can tell

**Comment by IBBoard** [comment] 2021-03-14 18:42
Okay, can you try reducing the sleep to one second each time and confirm that it definitely gets withdrawn and replaced, rather than just being a coincidence with the timeout?

On Gnome I could tell it was working because I could see the state during the pauses when it was removed or replaced. The replaced one instantly takes away the old one and puts the new one there whereas a new one with a different ID would be queued until the previous one timed out (but remained in the "tray") or was dismissed.
