### ISSUE TITLE
question: possible to use read only?

### ISSUE THREAD

**Issue by lonix1** [IBBoard/cawbird#216] opened 2020-11-26 05:27 UTC
Question.

Is it possible to use the app in "read only" mode? i.e. without logging in?

Twitter is usable even by those who don't have accounts.

**Comment by CodedOre** [comment] 2020-11-26 11:08
**Quick answer:** No.

**Long answer:**
Technically yes, as the Twitter API theoretically allows for API-Calls made over an token created for the app.

However this token authentication only allows for a very small set of actions before the rate limit kicks in. At the end it is supposed for non-interactive use, such as programs analyzing tweets, not to be a "do not log in"-option.

**Comment by IBBoard** [comment] 2020-11-26 18:40
Duplicate of #146

**Closed by IBBoard** 2020-11-26 18:40 UTC
Labels: duplicate, wontfix
