### ISSUE TITLE
Flatpak 100% cpu utilization on all cores when switching accounts

### ISSUE THREAD

**Issue by trst** [IBBoard/cawbird#77] opened 2020-01-20 15:44 UTC
I've been testing Cawbird across arch's local package and the Flatpak version, and noticed that the latter will light up all 4 cores on my Thinkpad when I switch between accounts and on first load.

The offending process is:
`/app/bin/cawbird --gapplication-service`

This behaviour is not replicated in the package from the Arch repositories.

Is there any other debugging information I can provide that would prove helpful?

Thank you for all your hard work! I truly appreciate it :raised_hands:

**Comment by IBBoard** [comment] 2020-01-20 18:43
Huh. I get a brief spike from the native version, but only on a single core. It's kind of to be expected to some degree as it will be downloading all of the tweets etc for your other account (Cawbird was designed to just monitor one account at once).

I don't know much (anything) about Flatpak. It's basically a community package, but I have the ability to update the referenced version.

If there's an equivalent to `G_MESSAGES_DEBUG=cawbird cawbird` (running Cawbird with the `G_MESSAGES_DEBUG` set to "cawbird") then that might show something. Failing that then @p1u3o or someone else might be able to advise about debugging Flatpak.

**Comment by p1u3o** [comment] 2020-01-21 09:19
I can see a spike in CPU utilization when switching accounts, but it doesn't last longer than a second.

There is a few of "Error performing TLS handshake: An unexpected TLS packet was received. (rest-proxy-error-quark - 4)", but an updated runtime with the fixed gnutls should be out any day now.

Maybe that's the cause?

**Comment by IBBoard** [comment] 2020-01-21 18:54
If you're still getting those TLS warnings (tracked in bug #9, but not actually our bug) then that would increase the amount of time that the CPU spikes for as it'll try again with each request.

**Comment by p1u3o** [comment] 2020-01-21 19:06
Here's the upstream bug report for getting the runtime updated.

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/953

**Comment by trst** [comment] 2020-01-22 00:52
I've run cawbird locally with the debug variable. Again no issue with the native package. The Flatpak has spun up 10+ PIDs I've observed in htop after switching accounts. The debug output is mostly the json response from Twitter's API, there are a few errors mostly related to media fetching. Could this be the source of the slowdown? a long timeout or a bad http response?
```
(cawbird:2): cawbird-DEBUG: 17:49:11.767: Request on 'https://pbs.twimg.com/media/EO1-bK7XsAEo4J_.jpg' returned status 'Message Corrupt'
```

@IBBoard I am seeing those random TLS issues, so perhaps that explains the length of time that the CPU is pegged. If the issue is upstream, then maybe it's better to close the issue for now and I can reopen if necessary in the future.

**Comment by IBBoard** [comment] 2020-01-22 18:57
If it's trying to fetch a lot of images and getting a lot of bad requests then that could extend the high load.

I'm surprised that there are multiple PIDs appearing, though. I'm not aware of Cawbird spawning subprocesses, just using threads. I've just checked and I don't appear to get multiple PIDs from the native build.

I'll close this for now on the assumption that it's expected behaviour combined with a TLS issue.

**Closed by IBBoard** 2020-01-22 18:57 UTC
Labels: info required
