### ISSUE TITLE
Strange graphical misbehavior at 300% scaling

### ISSUE THREAD

**Issue by glasserc** [IBBoard/cawbird#171] opened 2020-07-02 14:51 UTC
**Describe the bug**
I just installed `cawbird` using the build from OBS. (I also experience the same behavior when using the Snap.) Scrolling through the timeline, there's strange graphical behavior where tweet contents disappear and reappear as they move or as the mouse moves over them.

![Screenshot from 2020-07-02 10-29-15](https://user-images.githubusercontent.com/17006/86372190-db8b5000-bc4f-11ea-9fdb-a6dd5d634d23.png)

I don't think it's anything specific to my timeline because I'm able to view it fine on another computer (NixOS, also running Corebird 1.1.0).

**System details:**
 - OS: Ubuntu 20.04
 - Graphics hardware: Intel Iris Plus Graphics G7
 - Version: 1.1.0
 - Package type: .deb from OBS

**Comment by IBBoard** [comment] 2020-07-02 17:26
I've never seen anything like that before! It suggests a GTK/graphics oddity to me.

What hardware is your other machine running?

What output do you get when that happens if you run Cawbird from the command-line with the command `cawbird`? If that doesn't show anything, what about if you run `G_MESSAGES_DEBUG=cawbird cawbird`?

After that, we're probably going to have to get in to the realms of using the GTK Debugger to see what widgets are there and why they're not rendering.

**Comment by glasserc** [comment] 2020-07-02 17:54
The machine that has the problems is a Dell XPS 13 Developer Edition. The one that doesn't is a Thinkpad X1 Carbon and its graphics card is a Intel UHD Graphics 620 (rev 07).

Running `cawbird` at the command line only prints this message:

`(cawbird:39252): Gdk-CRITICAL **: 13:49:38.768: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed`

Doing `G_MESSAGES_DEBUG=cawbird cawbird` doesn't print out anything that looks especially useful, and certainly nothing when texts appear/disappear:

```
(cawbird:40121): cawbird-DEBUG: 13:52:31.369: Cawbird.vala:265: startup      ~ ~

(cawbird:40121): Gdk-CRITICAL **: 13:52:31.377: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
(cawbird:40121): cawbird-DEBUG: 13:52:31.377: New proxy consumer-key: Vf9torDW2ZOw32DfhUtI9csL8
(cawbird:40121): cawbird-DEBUG: 13:52:31.377: New proxy consumer-key: Vf9torDW2ZOw32DfhUtI9csL8
(cawbird:40121): cawbird-DEBUG: 13:52:31.379: Creating stream for EthanIsMumbling
(cawbird:40121): cawbird-DEBUG: 13:52:31.379: Loading timeline tweets on start
(cawbird:40121): cawbird-DEBUG: 13:52:31.379: Loading timeline tweets
(cawbird:40121): cawbird-DEBUG: 13:52:31.380: Loading mention tweets on start
(cawbird:40121): cawbird-DEBUG: 13:52:31.380: Loading mention tweets
(cawbird:40121): cawbird-DEBUG: 13:52:31.380: Loading favourited tweets on start
(cawbird:40121): cawbird-DEBUG: 13:52:31.380: Loading favourited tweets
(cawbird:40121): cawbird-DEBUG: 13:52:31.380: Loading DMs on start
(cawbird:40121): cawbird-DEBUG: 13:52:31.380: Loading DM tweets
(cawbird:40121): cawbird-DEBUG: 13:52:31.380: Adding timeout for timeline
(cawbird:40121): cawbird-DEBUG: 13:52:31.380: Adding timeout for mentions
(cawbird:40121): cawbird-DEBUG: 13:52:31.380: Adding timeout for favourites
(cawbird:40121): cawbird-DEBUG: 13:52:31.380: Adding timeout for DMs
(cawbird:40121): cawbird-DEBUG: 13:52:31.853: Account.vala:516: Add 0 disabled_rts ids
(cawbird:40121): cawbird-DEBUG: 13:52:31.853: Account.vala:485: Add 33 blocked ids
(cawbird:40121): cawbird-DEBUG: 13:52:31.981: Account.vala:454: Add 0 muted ids
(cawbird:40121): cawbird-DEBUG: 13:52:31.988: Got 28 mention tweets
(cawbird:40121): cawbird-DEBUG: 13:52:32.194: Got 28 favourited tweets
(cawbird:40121): cawbird-DEBUG: 13:52:32.261: Got 28 timeline tweets
(cawbird:40121): cawbird-DEBUG: 13:52:32.803: Got 18 DMs
(cawbird:40121): cawbird-DEBUG: 13:52:32.803: New DM with type: message_create
(cawbird:40121): cawbird-DEBUG: 13:52:32.804: New DM with type: message_create
(cawbird:40121): cawbird-DEBUG: 13:52:32.804: New DM with type: message_create
(cawbird:40121): cawbird-DEBUG: 13:52:32.804: New DM with type: message_create
(cawbird:40121): cawbird-DEBUG: 13:52:32.805: New DM with type: message_create
(cawbird:40121): cawbird-DEBUG: 13:52:32.805: New DM with type: message_create
(cawbird:40121): cawbird-DEBUG: 13:52:32.805: New DM with type: message_create
(cawbird:40121): cawbird-DEBUG: 13:52:32.805: New DM with type: message_create
(cawbird:40121): cawbird-DEBUG: 13:52:32.806: New DM with type: message_create
(cawbird:40121): cawbird-DEBUG: 13:52:32.806: New DM with type: message_create
(cawbird:40121): cawbird-DEBUG: 13:52:32.806: New DM with type: message_create
(cawbird:40121): cawbird-DEBUG: 13:52:32.807: New DM with type: message_create
(cawbird:40121): cawbird-DEBUG: 13:52:32.807: New DM with type: message_create
(cawbird:40121): cawbird-DEBUG: 13:52:32.807: New DM with type: message_create
(cawbird:40121): cawbird-DEBUG: 13:52:32.808: New DM with type: message_create
(cawbird:40121): cawbird-DEBUG: 13:52:32.808: New DM with type: message_create
(cawbird:40121): cawbird-DEBUG: 13:52:32.808: New DM with type: message_create
(cawbird:40121): cawbird-DEBUG: 13:52:32.809: New DM with type: message_create
(cawbird:40121): cawbird-DEBUG: 13:52:33.078: Removing avatar with id 704391334128394240 from cache
(cawbird:40121): cawbird-DEBUG: 13:52:33.081: Removing avatar with id 19380775 from cache
(cawbird:40121): cawbird-DEBUG: 13:52:33.084: Removing avatar with id 453473029 from cache
(cawbird:40121): cawbird-DEBUG: 13:52:33.273: Removing avatar with id 1236101 from cache
(cawbird:40121): cawbird-DEBUG: 13:52:33.297: Removing avatar with id 1069636036291112960 from cache
(cawbird:40121): cawbird-DEBUG: 13:52:33.414: Removing avatar with id 37053360 from cache
(cawbird:40121): cawbird-DEBUG: 13:52:33.421: Removing avatar with id 390039185 from cache
(cawbird:40121): cawbird-DEBUG: 13:52:33.429: Removing avatar with id 461281625 from cache
(cawbird:40121): cawbird-DEBUG: 13:52:33.435: Removing avatar with id 17393219 from cache
(cawbird:40121): cawbird-DEBUG: 13:52:33.441: Removing avatar with id 29417177 from cache
(cawbird:40121): cawbird-DEBUG: 13:52:33.442: Removing avatar with id 7587032 from cache
(cawbird:40121): cawbird-DEBUG: 13:52:33.447: Removing avatar with id 536904693 from cache
(cawbird:40121): cawbird-DEBUG: 13:52:33.449: Removing avatar with id 15041941 from cache
(cawbird:40121): cawbird-DEBUG: 13:52:33.454: Removing avatar with id 16071026 from cache
(cawbird:40121): cawbird-DEBUG: 13:52:33.455: Removing avatar with id 25753805 from cache
(cawbird:40121): cawbird-DEBUG: 13:52:33.461: Removing avatar with id 2791499260 from cache
(cawbird:40121): cawbird-DEBUG: 13:52:33.463: Removing avatar with id 22775788 from cache
(cawbird:40121): cawbird-DEBUG: 13:52:33.468: Removing avatar with id 20790079 from cache
(cawbird:40121): cawbird-DEBUG: 13:52:33.470: Removing avatar with id 16484216 from cache
```

Can you recommend a link about how to use the GTK Debugger? I've done a little bit of GTK development a long time ago but never used a GTK-specific debugging tool.

**Comment by IBBoard** [comment] 2020-07-02 17:59
It's called the "GTK Inspector". It's normally part of the GTK "devel" package.

Basically you install it, enable it, then Ctrl+Shift+I will bring it up (like the DOM Inspector in Firefox, if you've done any HTML). Swap to "CSS Nodes" in the drop-down and see whether the other elements of the tweets appear and which areas get highlighted.

https://wiki.gnome.org/Projects/GTK/Inspector

Is there anything specific that triggers this behaviour? Is it when you scroll fast, or just generally when you scroll? And in case it's something like a VRAM problem, can you try disabling image display and see whether it still happens?

**Comment by glasserc** [comment] 2020-07-02 18:18
It happens pretty much immediately on startup. Scrolling up or down causes different parts of things to show or hide.

The elements appear to show up in the inspector and clicking on them causes GTK to blink them, which makes them show up.

![2020-07-02 inspected](https://user-images.githubusercontent.com/17006/86395644-96c2e180-bc6e-11ea-9237-3984833d41a1.gif)

The same behavior occurs with "Show inline media: Hide in timeline".

I wasn't able to get them to blink when in "CSS Nodes" mode. Am I supposed to do something different in that mode?

**Comment by glasserc** [comment] 2020-07-02 18:36
I couldn't figure out how to record the behavior in a way that I could upload to Github, but here's a 25 MB .gif: https://send.firefox.com/download/ef58445d98b860cf/#RFMhH4lZA2x_eyttcTwJMw

I'm still not able to precisely guess what the trigger is. It does seem like mouseover contributes and maybe so does scrolling faster.

**Comment by IBBoard** [comment] 2020-07-04 14:00
A 25MB GIF? Wow!

The previous GIF makes it look like something isn't repainting properly, and then when you select it in the inspector then it flashes it and so it forces it to repaint. (I thought CSS Nodes did the flashing as well, but I guess it doesn't)

Your newer GIF looked like it was scrolling quite slowly, so it's not a "long way off the screen and suddenly in view" problem.

I think it is going to be tricky to recreate this. If you've worked with GTK apps before then are you able to build local versions of Cawbird with patches?

**Comment by glasserc** [comment] 2020-07-06 19:03
Yes I think so. I just built it from source (and can confirm that I see the same behavior with current `master`.

**Comment by kortewegdevries** [comment] 2020-07-07 16:44
> Yes I think so. I just built it from source (and can confirm that I see the same behavior with current master).

I did a build too on my main laptop running Xubuntu 20.04 AMD/Mesa hybrid graphics, unfortunately couldn't reproduce for OBS,git or flatpak. Any other Gtk applications showing same behaviour?

**Comment by IBBoard** [comment] 2020-07-07 18:38
Okay, at least you can rebuild it once I get a patch and we've confirmed that it's not just the packaged versions.

Initially it would just be some options for debugging rather than a fix, because I don't have a clue what's going on beyond "GTK and/or your graphics card are doing something _really_ weird"!

**Comment by glasserc** [comment] 2020-08-24 23:06
I just tried on master and see the same behavior.

**Comment by IBBoard** [comment] 2020-08-27 18:20
Huh. Okay.

Can you build the `bug142-memory-usage` branch, run it, go to Settings and set "Show inline media" to "Always Hide", then restart Cawbird and see if it still happens?

(I'm not trying to fix this in that branch, but it has some changes to image loading, and the only time I've got close to that behaviour was when I really screwed up image handling! So I want to see what happens if we disable all image loading)

**Comment by glasserc** [comment] 2020-08-27 18:29
I tried it and the behavior still happens. Since you brought up image loading, how about the user avatars? Those are still visible.

**Comment by IBBoard** [comment] 2020-08-27 18:32
True. Probably quite hard to remove *all* images without extensive code edits! The buttons almost certainly become pixbuf images at some point, so we probably can't remove all of them.

Annoying that it still happens, though. I can't find any other reports of GTK glitching out. It's not obviously image loading. It's affecting all widgets, so it's not to do with the "scrollable" that we put around the tweet text.

Something isn't calling the repaint correctly somewhere, but in general we don't explicitly call paint because GTK does that for us.

**Comment by IBBoard** [comment] 2020-11-14 15:12
@glasserc Can you check whether the latest "master" code still shows these issues? It's a long-shot, but I'm wondering whether the "initialise X" code might fix this as well.

**Comment by glasserc** [comment] 2020-11-17 14:33
It still shows some kind of related issue although I'm not sure it's 100% the same issue. When it first comes up, it looks mostly OK, but when I scroll, it starts to blank out parts and I think it's redrawing different tweets in the same screen area.

I got a prompt to upgrade to the next Ubuntu version. I'll try again once I do that (sometime in the next few weeks?).

**Comment by IBBoard** [comment] 2020-11-18 18:54
Drawing multiple tweets in the same area sounds odd. The only time I've had tweets "overflow" was while I was trying to get the 'responsive' design working and recalculating heights. But that should all be fixed now.

I guess we'll see whether it's install-specific and whether an upgraded Ubuntu fixes it.

**Comment by IBBoard** [comment] 2020-12-27 19:02
Have you been able to upgrade Ubuntu yet? Has it gone away?

**Comment by glasserc** [comment] 2020-12-29 05:28
I took the plunge today so I could respond to this bug! I think I might have a new clue, but maybe not. Just for completeness, here's the whole story: I started the upgrade and walked away and I guess it finished by itself and restarted the machine, but it failed to boot or something. I had to hard-power it off. It mostly came up correctly after that, but there was something messed up about the HiDPI scaling options. The GNOME Shell would scale correctly but applications like gnome-terminal or Firefox would not scale. I fiddled with the settings a little bit, leaving them at 200% instead of my normal 300%, and I spent a couple hours trying to figure out what was going on, but couldn't figure it out. I did discover a workaround (changing the screen resolution) but was hesitant to do that unless I had to. I figured I would reboot just in case, but I checked for updates first and apparently some were outstanding (?), so I applied them and then restarted.

When the machine came up this time, the HiDPI scale worked fine (which is a huge relief of course). Then I tried Cawbird (the distro-provided one) and it seemed OK! But everything was a little harder to read than I was used to because it was at 200% scale instead of 300%. So then I changed it to 300% and ... lo and behold, I saw the same problems in Cawbird that I had seen before. I confirmed by building most recent mainline and yeah, I'm still seeing these glitches.

Is it possible that there's something about the HiDPI scaling code in GTK that's causing the problem? Even at 200% it seemed like quote tweets were a little bit bigger than the space allocated for them (the last line was getting clipped).

Thanks for continuing to follow up on this!

**Comment by IBBoard** [comment] 2020-12-29 10:13
So 200% is fine, but 300% shows the missing UI components again? Odd. It suggests we're triggering some kind of odd GTK bug. We have some bits of code that handle 200% scaling (mainly loading higher-res icons) but I'm not familiar with how some of it works.

Does the quoted tweet size issue ever fix itself (e.g. when you click on a tweet)? We had some oddities that I fixed in #202 that came about because I tried to make a "responsive" UI for #57, but it's possible that my "fix" only works at 100% scaling. The next size allocation from GTK always seemed to fix it, though.

**Comment by glasserc** [comment] 2020-12-29 15:01
Yes, at 200% it's fine but 300% shows tweets blank out and disappear.

Here's a screenshot of the artifact I saw at 200%.

![Screenshot from 2020-12-29 09-33-55](https://user-images.githubusercontent.com/17006/103292437-c2274e80-49bb-11eb-97c7-645053f791db.png)

However, I only see it in the distro-shipped version of Cawbird. The version I built from master doesn't have that issue. I have more screenshots of circumstances when it happens and what it does when you click on the tweet but since it doesn't happen on master I won't post them (although I will if you want).

**Comment by IBBoard** [comment] 2020-12-29 16:32
What's the distro shipping versus what you're building? Unless the distro is shipping something newer than 1.2.1 (i.e. a Git build) then they won't have the fix that resolved some of that for #202.

Are other apps having issues at 300% or just Cawbird?

**Comment by glasserc** [comment] 2020-12-29 20:37
The distro build is listed as `1.2.1-1+7.1`. I'm 100% sure what I'm seeing is the same as #202 and that would explain why building from git doesn't demonstrate the behavior.

I've been running at 300% probably since I got this laptop back in June and I haven't noticed any other problems of this kind. Some proprietary applications (Zoom, Steam) don't cope well with HiDPI, but usually they just look very small.

**Comment by IBBoard** [comment] 2020-12-30 11:25
Just for interest, can you try running the `bug204-slow-focus-painting-alt-alt` branch? I'm wondering whether 300% scaling is too much when we've got lots of pages in the stack that we swap between. Having so many pages is causing other problems, so that branch removes most of them.

**Comment by glasserc** [comment] 2020-12-30 15:15
I just tried it, and it demonstrates the same behavior as far as I can tell.

**Comment by IBBoard** [comment] 2020-12-31 11:32
It was a long shot 🙂

**Comment by IBBoard** [comment] 2020-12-31 19:51
I've asked on the Gnome forums. We'll see whether anyone there has any more ideas.

https://discourse.gnome.org/t/widgets-not-rendering-at-300-scale/5187

**Comment by IBBoard** [comment] 2021-01-01 13:10
Based on Badert's response to the Gnome thread, can you check the new `bug171-300pc-scaling-issues` branch? I *think* I've got all of the problem areas.

**Comment by glasserc** [comment] 2021-01-01 15:27
Yes, this is a lot better! I haven't seen any issues so far.

**Comment by IBBoard** [comment] 2021-01-01 16:19
Okay, I'll merge this and close it, then. Re-open it if you find any bits I missed.

**Closed** 2021-01-01 16:22 UTC
Labels: bug, info required

**Comment by glasserc** [comment] 2021-01-04 16:58
So far, so good. Thanks! This is a great way to kick off the new year!
