### ISSUE TITLE
Feature Request. Taskbar notification

### ISSUE THREAD

**Issue by rahulrajpl** [IBBoard/cawbird#54] opened 2019-11-02 04:09 UTC
I would love to see a taskbar icon and run the application in the background. Just the way 'slack' or 'dropbox' clients are there at the top right corner in the below screenshot.

![image](https://user-images.githubusercontent.com/279503/68065801-49dfe180-fd54-11e9-9885-39c7a04597f6.png)

**Comment by IBBoard** [comment] 2019-11-02 09:47
Dupe of #45

**Closed by IBBoard** 2019-11-02 09:47 UTC
Labels: duplicate
