### ISSUE TITLE
Show youtube video thumbnail

### ISSUE THREAD

**Issue by philipzae** [IBBoard/cawbird#133] opened 2020-04-09 13:50 UTC
**Is your feature request related to a problem? Please describe.**
I'm unable to see a preview of the youtube video before clicking on the link

**Describe the solution you'd like**
The preview image can be displayed as long as no other media is already attached to the tweet

**Describe alternatives you've considered**
None

**Additional context**
https://twitter.com/Schykle/status/1247978160123043841
![preview](https://imgur.com/rXee45V.png)

https://twitter.com/Xubuntu/status/1247071545715052552
![preview](https://imgur.com/pJreUIL.png)

Thumbnail can easily be linked to like so

http://i3.ytimg.com/vi/fepSP7jKjSQ/maxresdefault.jpg
and
http://i3.ytimg.com/vi/hXLiqjOkSmg/maxresdefault.jpg

**Comment by IBBoard** [comment] 2020-04-09 15:47
Duplicate of #15

**Closed by IBBoard** 2020-04-09 15:47 UTC
Labels: duplicate
