### ISSUE TITLE
Dock to tray when close

### ISSUE THREAD

**Issue by bonelifer** [IBBoard/cawbird#252] opened 2020-12-22 23:17 UTC
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to dock cawbird to the tray.

**Describe the solution you'd like**
Ability to dock cawbird to the tray when close button used.

**Comment by IBBoard** [comment] 2020-12-23 10:18
Duplicate of #45

**Closed by IBBoard** 2020-12-23 10:19 UTC
Labels: duplicate
