### ISSUE TITLE
Cropped messages

### ISSUE THREAD

**Issue by philipzae** [IBBoard/cawbird#296] opened 2021-01-20 16:07 UTC
I regularly get cropped messages when opening up a [tweet](https://twitter.com/omgubuntu/status/1351601377353592832) which has replies. Scrolling up and down doesn't solve the problem

![image](https://user-images.githubusercontent.com/4412114/105201820-bc57ff80-5b5a-11eb-99c8-56bef9dddfed.png)

![image](https://user-images.githubusercontent.com/4412114/105201954-e1e50900-5b5a-11eb-91a1-179e42ee3910.png)

but if I wait long enough in the thread, then all is fine.

![image](https://user-images.githubusercontent.com/4412114/105202123-13f66b00-5b5b-11eb-859e-27550d48096a.png)

**Comment by IBBoard** [comment] 2021-01-20 18:32
Which version are you running? This looks like a recurrence of #202, which was caused by the changes in #57.

It fixes itself later because something triggers a reallocation of the widgets and it gets the calculations right this time. Which is odd, because if you're not resizing the window then we should always be using the default GTK calculations.

**Comment by philipzae** [comment] 2021-01-20 20:37
1.3 with the image always center patch. :D

**Comment by IBBoard** [comment] 2021-01-21 19:21
Okay. If it's 1.3 then it should include the patch.

Although… it looks like your window is narrow enough that it's in "responsive" view. I thought I'd fixed a bug with starting in responsive mode after I'd marked #202 as fixed, but maybe there's still something related lingering around.

**Comment by IBBoard** [comment] 2021-01-23 18:42
I can't recreate it at the moment. Even with that exact tweet and the same 362px width (using Master).

![Screenshot from 2021-01-23 18-41-34](https://user-images.githubusercontent.com/388582/105610985-b3f60380-5daa-11eb-95b6-9392bb61f594.png)

**Comment by IBBoard** [comment] 2021-01-23 18:53
Can you try that branch and see what output you get about preferred heights and allocation? If you're not resizing then I'm expecting it to mostly go down the GTK branches of the IF statements rather than our custom code.

**Comment by philipzae** [comment] 2021-01-24 02:07
I still saw it happen in different places, but nothing came out in the terminal.

**Comment by IBBoard** [comment] 2021-01-24 16:24
Is there any debug output at all? You might need to add `G_MESSAGE_DEBUG=cawbird` as well so that it shows debug level messages. I'm definitely getting output.

**Comment by philipzae** [comment] 2021-01-24 19:25
Didn't make a difference.

![image](https://user-images.githubusercontent.com/4412114/105641036-5c839080-5e9b-11eb-8e9a-c29b2caf005c.png)

**Comment by IBBoard** [comment] 2021-01-24 19:31
Sorry, typo - `G_MESSAGES_DEBUG=cawbird` (plural messages)

**Comment by IBBoard** [comment] 2021-01-24 19:35
I've just noticed that I do occasionally get the wrong size in the Settings window. That *might* give me enough to debug from.

But I'm not seeing it anywhere else, so I don't know what's different there.

**Comment by philipzae** [comment] 2021-01-25 12:57
The last replied tweet was cropped for maybe 30 seconds and I didn't see any output come out when it became whole.
![image](https://user-images.githubusercontent.com/4412114/105708239-94d3af00-5f2d-11eb-9837-963489e1b575.png)

I simply visit omgubuntu's twitter account and then open up one of their tweets and when the reply tweets appear, many a time, some of them will be cropped.

![image](https://user-images.githubusercontent.com/4412114/105708603-20e5d680-5f2e-11eb-81d5-edb2e0fe34ca.png)

**Comment by IBBoard** [comment] 2021-01-25 19:55
That can't be the right build, then. Or you already had an instance of Cawbird open and it just opened a new window of the other instance. Because I see stuff like this just from the home timeline:
```
⋮
(cawbird:4243): cawbird-DEBUG: 18:52:14.069: TweetListEntry.vala:850: Preferred height for 1353005101187821568: calculated 105 vs base of 105
(cawbird:4243): cawbird-DEBUG: 18:52:14.069: TweetListEntry.vala:850: Preferred height for 1352719664690950144: calculated 86 vs base of 86
(cawbird:4243): cawbird-DEBUG: 18:52:14.070: TweetListEntry.vala:850: Preferred height for 1352713584258637824: calculated 86 vs base of 105
(cawbird:4243): cawbird-DEBUG: 18:52:14.070: TweetListEntry.vala:850: Preferred height for 1352627556080615429: calculated 144 vs base of 144
(cawbird:4243): cawbird-DEBUG: 18:52:14.070: TweetListEntry.vala:850: Preferred height for 1352626477662167041: calculated 143 vs base of 143
(cawbird:4243): cawbird-DEBUG: 18:52:14.071: TweetListEntry.vala:850: Preferred height for 1352620335816966146: calculated 87 vs base of 87
(cawbird:4243): cawbird-DEBUG: 18:52:14.071: TweetListEntry.vala:850: Preferred height for 1352270227913011200: calculated 86 vs base of 86
(cawbird:4243): cawbird-DEBUG: 18:52:14.072: TweetListEntry.vala:850: Preferred height for 1351996414612692995: calculated 86 vs base of 86
(cawbird:4243): cawbird-DEBUG: 18:52:14.072: TweetListEntry.vala:850: Preferred height for 1351893097966415882: calculated 124 vs base of 143
(cawbird:4243): cawbird-DEBUG: 18:52:14.072: TweetListEntry.vala:850: Preferred height for 1351832142758739968: calculated 86 vs base of 86
(cawbird:4243): cawbird-DEBUG: 18:52:14.073: TweetListEntry.vala:850: Preferred height for 1351255090506706945: calculated 124 vs base of 143
(cawbird:4243): cawbird-DEBUG: 18:52:14.073: TweetListEntry.vala:850: Preferred height for 1351138432203055111: calculated 105 vs base of 124
(cawbird:4243): cawbird-DEBUG: 18:52:14.073: TweetListEntry.vala:850: Preferred height for 1350223079583178753: calculated 162 vs base of 162
(cawbird:4243): cawbird-DEBUG: 18:52:14.074: TweetListEntry.vala:850: Preferred height for 1350080949653037064: calculated 124 vs base of 124
(cawbird:4243): cawbird-DEBUG: 18:52:14.074: TweetListEntry.vala:850: Preferred height for 1349453526297096192: calculated 181 vs base of 181
(cawbird:4243): cawbird-DEBUG: 18:52:14.074: TweetListEntry.vala:850: Preferred height for 1349383320791035904: calculated 86 vs base of 102
(cawbird:4243): cawbird-DEBUG: 18:52:14.075: TweetListEntry.vala:850: Preferred height for 1348438656340664321: calculated 143 vs base of 162
(cawbird:4243): cawbird-DEBUG: 18:52:14.075: TweetListEntry.vala:850: Preferred height for 1348437734516523013: calculated 162 vs base of 181
(cawbird:4243): cawbird-DEBUG: 18:52:14.075: TweetListEntry.vala:850: Preferred height for 1348437087935221768: calculated 124 vs base of 143
(cawbird:4243): cawbird-DEBUG: 18:52:14.076: TweetListEntry.vala:850: Preferred height for 1348431906560421895: calculated 124 vs base of 143
(cawbird:4243): cawbird-DEBUG: 18:52:14.076: TweetListEntry.vala:850: Preferred height for 1348430412729765888: calculated 143 vs base of 162
(cawbird:4243): cawbird-DEBUG: 18:52:14.076: TweetListEntry.vala:850: Preferred height for 1348429522308362240: calculated 86 vs base of 86
(cawbird:4243): cawbird-DEBUG: 18:52:14.077: TweetListEntry.vala:850: Preferred height for 1348429449809821697: calculated 105 vs base of 124
(cawbird:4243): cawbird-DEBUG: 18:52:14.077: TweetListEntry.vala:850: Preferred height for 1348419470088417282: calculated 162 vs base of 181
(cawbird:4243): cawbird-DEBUG: 18:52:14.077: TweetListEntry.vala:850: Preferred height for 1348413890099630080: calculated 143 vs base of 143
(cawbird:4243): cawbird-DEBUG: 18:52:14.078: TweetListEntry.vala:850: Preferred height for 1348330230021312512: calculated 86 vs base of 86
(cawbird:4243): cawbird-DEBUG: 18:52:14.078: TweetListEntry.vala:850: Preferred height for 1353714837981827072: calculated 73 vs base of 73
(cawbird:4243): cawbird-DEBUG: 18:52:14.079: TweetListEntry.vala:850: Preferred height for 1353639502506557440: calculated 146 vs base of 140
(cawbird:4243): cawbird-DEBUG: 18:52:14.079: TweetListEntry.vala:850: Preferred height for 1353618448014835712: calculated 758 vs base of 752
(cawbird:4243): cawbird-DEBUG: 18:52:14.079: TweetListEntry.vala:850: Preferred height for 1353353880978006016: calculated 124 vs base of 124
(cawbird:4243): cawbird-DEBUG: 18:52:14.080: TweetListEntry.vala:850: Preferred height for 1353351758177841152: calculated 73 vs base of 73
(cawbird:4243): cawbird-DEBUG: 18:52:14.080: TweetListEntry.vala:850: Preferred height for 1353326633655160835: calculated 73 vs base of 73
(cawbird:4243): cawbird-DEBUG: 18:52:14.080: TweetListEntry.vala:850: Preferred height for 1353326326426562560: calculated 208 vs base of 202
(cawbird:4243): cawbird-DEBUG: 18:52:14.081: TweetListEntry.vala:850: Preferred height for 1353296208178118661: calculated 73 vs base of 73
(cawbird:4243): cawbird-DEBUG: 18:52:14.081: TweetListEntry.vala:850: Preferred height for 1353116710665035776: calculated 105 vs base of 105
(cawbird:4243): cawbird-DEBUG: 18:52:14.081: TweetListEntry.vala:850: Preferred height for 1353114985879252993: calculated 652 vs base of 646
(cawbird:4243): cawbird-DEBUG: 18:52:14.082: TweetListEntry.vala:850: Preferred height for 1353044680842170368: calculated 759 vs base of 753
(cawbird:4243): cawbird-DEBUG: 18:52:14.082: TweetListEntry.vala:850: Preferred height for 1353041857379500032: calculated 622 vs base of 616
(cawbird:4243): cawbird-DEBUG: 18:52:14.082: TweetListEntry.vala:850: Preferred height for 1352993233274601472: calculated 73 vs base of 73
(cawbird:4243): cawbird-DEBUG: 18:52:14.083: TweetListEntry.vala:850: Preferred height for 1352991373478211584: calculated 907 vs base of 901
(cawbird:4243): cawbird-DEBUG: 18:52:14.083: TweetListEntry.vala:850: Preferred height for 1352900968648765441: calculated 86 vs base of 86
(cawbird:4243): cawbird-DEBUG: 18:52:14.084: TweetListEntry.vala:850: Preferred height for 1352899362226139136: calculated 73 vs base of 73
(cawbird:4243): cawbird-DEBUG: 18:52:14.084: TweetListEntry.vala:850: Preferred height for 1352899356039516160: calculated 73 vs base of 73
(cawbird:4243): cawbird-DEBUG: 18:52:14.084: TweetListEntry.vala:850: Preferred height for 1352879934461648896: calculated 73 vs base of 73
(cawbird:4243): cawbird-DEBUG: 18:52:14.085: TweetListEntry.vala:850: Preferred height for 1352830361940746244: calculated 73 vs base of 73
(cawbird:4243): cawbird-DEBUG: 18:52:14.085: TweetListEntry.vala:850: Preferred height for 1352820985611706368: calculated 73 vs base of 73
(cawbird:4243): cawbird-DEBUG: 18:52:14.086: TweetListEntry.vala:850: Preferred height for 1352815991521067008: calculated 73 vs base of 73
(cawbird:4243): cawbird-DEBUG: 18:52:14.086: TweetListEntry.vala:850: Preferred height for 1352748988856819712: calculated 357 vs base of 351
(cawbird:4243): cawbird-DEBUG: 18:52:14.086: TweetListEntry.vala:850: Preferred height for 1352721089605021702: calculated 73 vs base of 73
(cawbird:4243): cawbird-DEBUG: 18:52:14.087: TweetListEntry.vala:850: Preferred height for 1352719664690950144: calculated 86 vs base of 86
(cawbird:4243): cawbird-DEBUG: 18:52:14.087: TweetListEntry.vala:850: Preferred height for 1352681207994216449: calculated 787 vs base of 781
(cawbird:4243): cawbird-DEBUG: 18:52:14.088: TweetListEntry.vala:850: Preferred height for 1352660830152765448: calculated 509 vs base of 503
(cawbird:4243): cawbird-DEBUG: 18:52:14.088: TweetListEntry.vala:850: Preferred height for 1352625520731680770: calculated 105 vs base of 105
(cawbird:4243): cawbird-DEBUG: 18:52:14.088: TweetListEntry.vala:850: Preferred height for 1352623663959293954: calculated 73 vs base of 73
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:746: Using default GTK preferred height for width
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.089: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.090: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.090: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.090: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.090: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.090: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.090: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.090: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.090: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.090: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.090: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.090: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.090: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.090: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.090: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.090: TweetListEntry.vala:896: No custom size allocation
(cawbird:4243): cawbird-DEBUG: 18:52:14.090: TweetListEntry.vala:896: No custom size allocation
⋮
```

**Comment by philipzae** [comment] 2021-01-27 15:20
I pulled in the latest master and compiled it with 'ninja -C build' and ran it with the same debug command you provided and still can't see the TweetListEntry.vala debug lines. Well anyway you are seeing the output, so now its in your hands. :smile:

**Comment by IBBoard** [comment] 2021-01-27 18:42
I can see the output. But I also can't recreate the cropping!

But you said "master". Because it's debugging then the code for this is on a branch - `bug296-cropped-replies` 🙂

**Comment by IBBoard** [comment] 2021-02-13 15:28
Okay, based on debugging the Settings dialog behaviour, I *think* I've got it. I don't know why I don't see it in timelines. I wonder whether something triggers another calculate/allocate run and so it fixed itself before I ever saw anything wrong.

Can you check that and see if it fixes it?

**Comment by IBBoard** [comment] 2021-03-03 19:33
I've not been able to recreate this with the bug296 branch (even on the Settings page, where I was seeing it) so I've squashed and merged it and assumed it's fixed.

**Closed** 2021-03-03 19:32 UTC
Labels: info required
