### ISSUE TITLE
Popup images no longer open in vertical center of screen

### ISSUE THREAD

**Issue by philipzae** [IBBoard/cawbird#271] opened 2021-01-06 00:29 UTC
Xubuntu 20.04 with Cawbird 1.3.1+5.2

When I click on an image, the popup image appears on the right side of the screen rather in the vertical center of the screen.

![image](https://user-images.githubusercontent.com/4412114/103714296-bea55000-4fd7-11eb-9677-85de36701aeb.png)

**Comment by IBBoard** [comment] 2021-01-06 19:28
I'm trying to understand what I'm seeing there. Is that a screenshot of a desktop that you've opened, and it's aligned to the right-hand side rather than centralised? Does it do it with images that don't have scroll bars?

**Comment by IBBoard** [comment] 2021-01-07 21:02
Just looking at this again and… I think it's doing what it's supposed to. Maximised images are modal on the parent window. That means that the window manager will (normally) centralise them on the parent window (the main Cawbird timeline). If you've got Cawbird all the way to the right then it can't centralise the image without putting it off-screen. Which it won't do. So it puts it as central to the parent as possible, which is up against the right-hand side.

If we centralised all images on the screen and not on the window then small images on large monitors could end up miles away from the app, which would be annoying for most users.

That still appears to be vertically centred on the parent window.

**Comment by philipzae** [comment] 2021-01-08 08:43
Yes I believe it should centralize it on the screen and not based on where cawbird is placed. I believe it used to do that in a previous version as well.

Regarding the image appearing miles away from the app, that is fine as clicking anywhere inside or outside of the image will close the image popup.

**Comment by IBBoard** [comment] 2021-01-08 17:55
No, it never centralised on the screen in Gnome. It has always centralised on the app (to the best that it can).

As for the usefulness of appearing in the middle of the screen, I can see what you mean that it closes, but it's still not a good usability thing to make the user look across their screen just to see a picture. The result should (ideally) happen close to the action. And the way to do that is to centralise it over the app.

**Comment by philipzae** [comment] 2021-01-09 12:25
I can only guess, but I presume most users will have cawbird on the left or right side of the screen and when they open images and videos, many of them will be large and not placing them in the center is not a normal experience. You can see the tweetdeck interface or an html lightbox and they center the images and vidoes in the center of the screen.

**Comment by IBBoard** [comment] 2021-01-09 12:38
> most users will have cawbird on the left or right side of the screen

Which is why we anchor it to the window.

> many of them will be large and not placing them in the center is not a normal experience

"Normal experience" depends on context. And just because many will be large doesn't mean that they're all large, and the smaller ones will look ridiculous when put in the middle of the desktop, miles from the UI.

I'd argue that having to suddenly look across the screen isn't normal either. We don't (or shouldn't) put other dialogs miles away from the main window, because it's annoying to click a button and then have to have noticed where the dialog appeared. In large monitors, that can be effectively peripheral vision.

> You can see the tweetdeck interface or an html lightbox and they center the images and vidoes in the center of the screen.

HTML lightboxes centre in the middle of the browser. That's only the middle of the screen if you full-screen your browser. I've got a 1440p monitor at home, so I don't full-screen many apps at all. Even on 1080p I don't full-screen browsers because it is too wide to read comfortably.

We've also got to take multi-monitor users into account. At work (back in the days when I was in the office) I had dual 1440p monitors. We can't make the same assumptions as web and mobile apps.

This isn't a bug/regression, since the behaviour hasn't changed since the Corebird days.

And as a feature request, I'm not convinced by the arguments, so I'm going to close this.

**Closed by IBBoard** 2021-01-09 12:38 UTC
Labels: info required

**Comment by philipzae** [comment] 2021-01-10 08:02
Thanks for consideration. Guess i'll downgrade to 1.1 where it did work as expected.

**Comment by IBBoard** [comment] 2021-01-10 13:20
I'm slightly confused about why v1.1 is any better. Unless the changes for #122 affected the behaviour. But as far as I can remember then Cawbird and Corebird before it have always centered on the app in Gnome for the however many years (four? five?) that I've been using it.

You're going to miss out on a lot of new features and fixes if you stick with v1.1, though. Another option would be to maintain a custom one-line patch equivalent to 60c2e008e5f522b3817dd2d1a5bf94e7aba7cb4d, but which uses `CENTER` instead. It might need a change to `set_transient_for` calls as well, but I've not tested it, I don't know which takes priority, and I don't know what side-effects you'd have from removing the transient relationship.

**Comment by philipzae** [comment] 2021-01-11 19:58
v1.1 centers both images and videos in the center of the screen for me. Strangely, I never upgraded to 1.2 but did upgrade to 1.3 when I saw it mentioned on twitter. I got a hold of 1.2 but it is similar to 1.3 in not centering things. Not sure which individual patch caused this.

**Comment by IBBoard** [comment] 2021-01-11 20:20
It's almost certainly the attempts to fix #122. The tag history on 60c2e00 shows that it first appeared in v1.2.0. The last change before that to the media display is a fix for image widths that made it in to v1.0.5 (5519fb88).

**Comment by philipzae** [comment] 2021-01-12 10:33
It would be great if you could add a toggle/combobox in settings so that a user could set there preferred behaviour.

**Comment by IBBoard** [comment] 2021-01-12 18:58
Can you try a custom build with 60c2e00 removed? Just delete the one line that was added. Given that it appears to be the only change that was made for #122 and it still didn't quite get the right behaviour then it might be enough to get us back to "Gnome does the expected thing and other desktops do whatever is normal for them" behaviour.

**Comment by philipzae** [comment] 2021-01-13 10:50
I don't mind giving it a try if you can tell me how. I cloned the repo on my Xubuntu 21.04 system, but 'sudo apt build-dep cawbird' didn't pull down the necessary dependencies to build it with the 'meson build' command. There doesn't seem to be a deb-src entry equivalent for 'deb http://download.opensuse.org/repositories/home:/IBBoard:/cawbird/xUbuntu_20.10/ /' that is put into /etc/apt/sources.list.d/home:IBBoard:cawbird.list

![image](https://user-images.githubusercontent.com/4412114/104442137-12063800-55ae-11eb-8452-32a80975162f.png)

![image](https://user-images.githubusercontent.com/4412114/104442043-f4d16980-55ad-11eb-9fe6-22fdf55075ba.png)

**Comment by IBBoard** [comment] 2021-01-14 20:42
I don't know much about Ubuntu and deb-based systems. What's normally in a `deb-src` repo? I'd be surprised if OBS didn't support it. There's definitely a "[Sources](https://download.opensuse.org/repositories/home:/IBBoard:/cawbird/xUbuntu_20.10/Sources)" file in there and it lists the build-depends, and files like the dsc, tarball and diff.

**Comment by IBBoard** [comment] 2021-01-14 20:53
Okay, maybe OBS *doesn't* support Debian "source" repos ([source](https://en.opensuse.org/openSUSE:Build_Service_Debian_builds#Package_repositories))

Does it work to do an `apt install` based on the `Build-Dependes` line?

`debhelper (>= 11), gettext (>= 0.19.7), libglib2.0-dev (>= 2.44), libgstreamer-plugins-base1.0-dev, libgstreamer1.0-dev (>= 1.6), libgspell-1-dev, libgtk-3-dev (>= 3.20), libjson-glib-dev, libsoup2.4-dev, libsqlite3-dev, libxml2-utils, librest-dev, liboauth-dev, valac (>= 0.28), meson, ninja-build`

The format doesn't quite look right so you might have to remove the versions in brackets (if you're on any of the distros that we support then your libraries *should* be sufficiently up-to-date to meet the minimum versions)

**Comment by philipzae** [comment] 2021-01-15 23:07
> I don't know much about Ubuntu and deb-based systems. What's normally in a `deb-src` repo? I'd be surprised if OBS didn't support it. There's definitely a "[Sources](https://download.opensuse.org/repositories/home:/IBBoard:/cawbird/xUbuntu_20.10/Sources)" file in there and it lists the build-depends, and files like the dsc, tarball and diff.

Yes the source list here made it possible to compile it. thanks. would be good to add this list to the readme.md file.

So yes after commenting out that line, its centered correctly.

**Comment by IBBoard** [comment] 2021-01-16 09:51
> Yes the source list here made it possible to compile it. thanks. would be good to add this list to the readme.md file.

We already list the [build dependencies](https://github.com/IBBoard/cawbird#build-dependencies) in the README. We intentionally don't have distro-specific names because then we'd have to maintain the openSUSE versions and the Fedora versions and the Arch versions and the…

> So yes after commenting out that line, its centered correctly.

Okay. Since it didn't seem to do much for #122 anyway then I'll remove that commit.

**Comment by philipzae** [comment] 2021-01-16 13:09
> Okay. Since it didn't seem to do much for #122 anyway then I'll remove that commit.

I've sent in a patch that correctly fixes #122.
