### ISSUE TITLE
Please provide a flatpak through flathub

### ISSUE THREAD

**Issue by hfiguiere** [IBBoard/cawbird#24] opened 2019-09-04 19:43 UTC
Please provide a flatpak through flathub.

CoreBird used to be available this way.

See the archived project https://github.com/flathub/org.baedert.corebird

**Comment by IBBoard** [comment] 2019-09-06 18:24
I've never used Flatpak (or Snap or any of the others) but if people use it then it sounds sensible.

For now, though, I'm going to concentrate on the main app and [building native packages on OBS](https://software.opensuse.org/download.html?project=home%3AIBBoard%3Acawbird&package=cawbird). If someone wants to build a Flatpak in the meantime then I'll support where I can.

**Comment by felipehw** [comment] 2019-10-03 17:04
This would be a very good step :)
Gnome ecosystem has a very close relationship with Flatpak and many gnome users search for new gnome-like apps in Flathub!
Another point is that with a Flatpak package, we don't have to put a lot of effort to make a lot of packages for different releases of the many existing distros.

**Comment by IBBoard** [comment] 2019-10-03 18:19
Thanks to  @p1u3o, we've got the starts of a PR to add this.

I guess I need to work out how to submit to Flathub.

**Comment by p1u3o** [comment] 2019-10-03 18:23
Hey @IBBoard 

Submitting to Flathub is pretty easy. My PR should be good to merge after a few changes which I'll do in a moment.

One thing that would be handy is if the icon name could be the same as the app-id. This means the manifest file doesn't have to rename it and is the practice upstream GNOME apps have adopted.

**Comment by IBBoard** [comment] 2019-10-03 18:27
Ah, yes, the new "org.gnome.App" approach to icon naming. I hadn't thought about that.

Feel free to fix it in your PR as part of the Flatpak changes. I guess you'll need to rename the SVG, the PNGs under hicolor, and the render-icons.sh script. Or I can do it after the merge.

**Comment by p1u3o** [comment] 2019-10-03 19:32
@IBBoard is there any reason why you're generating pngs instead of just using the svg?

**Comment by IBBoard** [comment] 2019-10-03 19:36
Because Baedert did it that way, and he was involved in Gnome/GTK?

But no, not really. I'm used to PNGs (and despite some artist blogs I've seen saying otherwise, I prefer the Tango icons that were crafted to each size) but if SVG is all we need then we could go pure SVG.

**Comment by p1u3o** [comment] 2019-10-03 20:00
I don't think the pngs are needed and the svg can dropped into hicolor/scalable but I will leave that and renaming the icon to the app-id up to you. The manifest itself should be good to merge.

**Comment by TingPing** [comment] 2019-10-03 20:43
Nothing wrong with generating PNGs, they are faster to load and its not like the space savings matter.

**Comment by IBBoard** [comment] 2019-10-05 18:17
I've updated the app ID and icons.

As far as I can tell, that Flatpak config is for building locally, but Flathub wants a [tag-based "stable" config](https://github.com/flathub/flathub/wiki/App-Requirements#stable-releases-reproducible-builds)?

What's the normal practice there - keep this as the Dev one and submit a Production version to Flathub?

**Comment by p1u3o** [comment] 2019-10-05 18:21
You'll want to make a manifest just for Flathub that lives over there that pulls from a release tag rather than from disk.

I'm out at the moment, but when I get home I'll put something together as well as removing the un-needed gstreamer plugins, unless someone beats me to the punch.

**Comment by IBBoard** [comment] 2019-10-29 15:43
The latest PR has been merged. I still need to make the official release package, once I work out how it works and what needs to change in the config.

**Comment by LennyPenny** [comment] 2019-11-03 16:58
is there any pre-release we can try out in the meantime?

**Comment by IBBoard** [comment] 2019-11-03 17:04
There's a config in the repo now. It'll build Git Master, but that's currently stable. I guess that's effectively always a pre-release.

Unless Flatpak has some other concept of "pre-release"?

**Comment by p1u3o** [comment] 2019-11-25 13:16
A Flatpak has been submitted and approved on Flathub.

Sorry about the wait.
It should appear at https://flathub.org/apps/details/uk.co.ibboard.cawbird shortly.

**Comment by IBBoard** [comment] 2019-11-25 20:36
Thanks for building and submitting that! I guess I need to work out what needs maintaining now 😄

**Comment by p1u3o** [comment] 2019-11-25 20:39
The Flatpak is pretty easy to maintain. For each new release you just need to update the manifest file on the Flathub repository to point to that release.

Flathub automatically pulls all the app information and update notes from the appdata file.

**Comment by p1u3o** [comment] 2019-11-26 08:11
https://flathub.org/apps/details/uk.co.ibboard.cawbird is live so you can probably go ahead and close this issue.

A lot of GNOME apps have this in their README, if you want to use it.
https://flathub.org/assets/badges/flathub-badge-en.svg

**Closed** 2019-11-26 19:22 UTC
Labels: help wanted
